name: Deploy to Live Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Open Ownership
      uses: appleboy/ssh-action@master
      with:
        host: "172.16.12.129"
        username: "devops"
        password: ${{ secrets.SSH_LIVE_PASSWORD }}
        port: 22
        script: |
          cd /var/www/keloola-projects/bos.keloola.com
          echo ${{ secrets.SSH_LIVE_PASSWORD }} | sudo -S chown -R devops:devops storage bootstrap/cache
          
    - name: Git Pull
      uses: appleboy/ssh-action@master
      with:
        host: "172.16.12.129"
        username: "devops"
        password: ${{ secrets.SSH_LIVE_PASSWORD }}
        port: 22
        script: |
          cd /var/www/keloola-projects/bos.keloola.com
          git pull origin main

    - name: Install Dependencies
      uses: appleboy/ssh-action@master
      with:
        host: "172.16.12.129"
        username: "devops"
        password: ${{ secrets.SSH_LIVE_PASSWORD }}
        port: 22
        script: |
          cd /var/www/keloola-projects/bos.keloola.com
          php /home/devops/composer.phar update --no-interaction --prefer-dist --optimize-autoloader --no-dev --ignore-platform-reqs

    - name: Run Migrations
      uses: appleboy/ssh-action@master
      with:
        host: "172.16.12.129"
        username: "devops"
        password: ${{ secrets.SSH_LIVE_PASSWORD }}
        port: 22
        script: |
          cd /var/www/keloola-projects/bos.keloola.com
          echo "yes" | php artisan migrate

    - name: Clear Cache
      uses: appleboy/ssh-action@master
      with:
        host: "172.16.12.129"
        username: "devops"
        password: ${{ secrets.SSH_LIVE_PASSWORD }}
        port: 22
        script: |
          cd /var/www/keloola-projects/bos.keloola.com
          php artisan optimize:clear
          php artisan config:clear
          php artisan view:clear
          php artisan route:clear

    - name: Close Ownership
      uses: appleboy/ssh-action@master
      with:
        host: "172.16.12.129"
        username: "devops"
        password: ${{ secrets.SSH_LIVE_PASSWORD }}
        port: 22
        script: |
          cd /var/www/keloola-projects/bos.keloola.com
          echo ${{ secrets.SSH_LIVE_PASSWORD }} | sudo -S chown -R nginx:nginx storage bootstrap/cache

    - name: Update Supervisor
      uses: appleboy/ssh-action@master
      with:
        host: "172.16.12.129"
        username: "devops"
        password: ${{ secrets.SSH_LIVE_PASSWORD }}
        port: 22
        script: |
          echo ${{ secrets.SSH_LIVE_PASSWORD }} | sudo -S supervisorctl reread
          echo ${{ secrets.SSH_LIVE_PASSWORD }} | sudo -S supervisorctl update
          echo ${{ secrets.SSH_LIVE_PASSWORD }} | sudo -S supervisorctl restart bos.keloola.com-worker:*
